<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: yzs
 * Date: Mon, 03 Dec 2018 18:17:19 +0800
 */

$conf['title'] = 'NoteBook-Wiki';
$conf['lang'] = 'zh';
$conf['license'] = 'cc-by-sa';
$conf['breadcrumbs'] = 0;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['proxy']['user'] = 'yzs';
$conf['proxy']['pass'] = '<b>eXpzMTIz';

// end auto-generated content
